[package]
name = "robots-txt-tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
csv = "1.2.1"
junit-report = "0.8.2"
lenient_bool = "0.1.1"
texting_robots = "0.2.2"
time = { version = "0.3.4", features = ["formatting", "macros"] }
rayon = { version = "1.7.0" }
