name: GitHub Actions
run-name: ${{ github.ref }} is building
on: [push]
jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    steps:
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cargo build --release